### Site Settings ###
source              : ../
collections_dir     : docs
data_dir            : docs/_data
baseurl             : "/"
repository          : nh4ttruong
open_new_tab        : false

### Navbar Settings ###
nav_exclude:
  - docs/pages/tags.html
  - docs/pages/404.html
  - docs/pages/index.md
  - docs/pages/documentation/**

### Author Info ###
author:
  name              : Nhat Truong
  image             : https://i.imgur.com/V60Nk1V.jpg
  github            : nh4ttruong
### Posts ###
permalink: /blog/:title
### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name
### Analytics ###
analytics:
  enabled: true                                        # Set true to enable analytics
  google:
    tracking_id: G-6P2QMTRKX6
### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      comments: false                                   # Set to true to enable disqus comments
### Exclude from processing ###
exclude:
  - LICENSE
  - "*.log"
