### Posts ###
permalink: /blog/:title
### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name
### Analytics ###
analytics:
  enabled: true                                        # Set true to enable analytics
  google:
    tracking_id: G-6P2QMTRKX6
### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      comments: false                                   # Set to true to enable disqus comments
### Exclude from processing ###
exclude:
  - LICENSE
  - "*.log"